language: java
script:
- "./activator test"
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
after_success:
- openssl aes-256-cbc -K $encrypted_d1cac68f8ddc_key -iv $encrypted_d1cac68f8ddc_iv
  -in .travis/deploy.enc -out .travis/deploy -d
- chmod 600 .travis/deploy
- ssh -i .travis/deploy vu2003@madoka.whs.in.th gg/deploy.sh
